DROP TABLE T_USER;

CREATE TABLE T_USER (
	USER_ID	VARCHAR2(20)		NOT NULL,
	USER_PWD	VARCHAR2(20)		NULL,
	OFFICE_NO	NUMBER		NULL,
	USER_NM	VARCHAR2(40)		NULL,
	USER_PWD_HINT_CD	VARCHAR2(5)		NULL,
	USER_CELL_PHONE_NUM	VARCHAR2(20)		NULL,
	USER_BRTH	VARCHAR2(8)		NULL,
	USER_GENDER	VARCHAR2(1)		NULL,
	USER_ADDR	VARCHAR2(500)		NULL,
	USER_MAIL	VARCHAR2(50)		NULL,
	USER_AUTH_YN	VARCHAR2(1)		NULL,
	USER_AUTH_TYP	VARCHAR2(5)		NULL,
	USER_FIRST_LOING_DT	VARCHAR2(8)		NULL,
	USER_LAST_LOGIN_DT	DATE		NULL,
	USER_LOGIN_SESSION_KEY	VARCHAR2(200)		NULL,
	USER_LEAVE_YN	VARCHAR2(1)		NULL,
	USER_PWD_ERR_CNT	NUMBER		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_USER.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_USER.USER_PWD IS '비밀번호';

COMMENT ON COLUMN T_USER.OFFICE_NO IS '지점번호';

COMMENT ON COLUMN T_USER.USER_NM IS '사용자명';

COMMENT ON COLUMN T_USER.USER_PWD_HINT_CD IS '비밀번호찾기힌트코드';

COMMENT ON COLUMN T_USER.USER_CELL_PHONE_NUM IS '전화번호';

COMMENT ON COLUMN T_USER.USER_BRTH IS '생년월일';

COMMENT ON COLUMN T_USER.USER_GENDER IS '성별';

COMMENT ON COLUMN T_USER.USER_ADDR IS '주소';

COMMENT ON COLUMN T_USER.USER_MAIL IS '이메일';

COMMENT ON COLUMN T_USER.USER_AUTH_YN IS '관리자권한유무';

COMMENT ON COLUMN T_USER.USER_AUTH_TYP IS '권한타입';

COMMENT ON COLUMN T_USER.USER_FIRST_LOING_DT IS '가입일자';

COMMENT ON COLUMN T_USER.USER_LAST_LOGIN_DT IS '마지막로그인일자';

COMMENT ON COLUMN T_USER.USER_LOGIN_SESSION_KEY IS '로그인세션키';

COMMENT ON COLUMN T_USER.USER_LEAVE_YN IS '탈퇴여부';

COMMENT ON COLUMN T_USER.USER_PWD_ERR_CNT IS '비밀번호오류횟수';

COMMENT ON COLUMN T_USER.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_USER.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_USER.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_OFFICE;

CREATE TABLE T_OFFICE (
	OFFICE_NO	NUMBER		NOT NULL,
	HEAD_YN	VARCHAR2(1)		NULL,
	OFFICE_KOR_NM	VARCHAR2(100)		NULL,
	OFFICE_ENG_NM	VARCHAR2(100)		NULL,
	ADDR	VARCHAR2(500)		NULL,
	OPEN_DTE	VARCHAR2(8)		NULL,
	OFFICE_USE_YN	VARCHAR2(1)		NULL,
	ST_DTE	VARCHAR2(4)		NULL,
	ED_DTE	VARCHAR2(4)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_OFFICE.OFFICE_NO IS '지점번호';

COMMENT ON COLUMN T_OFFICE.HEAD_YN IS '본점여부';

COMMENT ON COLUMN T_OFFICE.OFFICE_KOR_NM IS '지점명';

COMMENT ON COLUMN T_OFFICE.OFFICE_ENG_NM IS '지점영문명';

COMMENT ON COLUMN T_OFFICE.ADDR IS '주소';

COMMENT ON COLUMN T_OFFICE.OPEN_DTE IS '오픈일시';

COMMENT ON COLUMN T_OFFICE.OFFICE_USE_YN IS '사용여부';

COMMENT ON COLUMN T_OFFICE.ST_DTE IS '시작시간';

COMMENT ON COLUMN T_OFFICE.ED_DTE IS '마감시간';

COMMENT ON COLUMN T_OFFICE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_OFFICE.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_OFFICE.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_MENU;

CREATE TABLE T_MENU (
	MENU_TYP	NUMBER		NOT NULL,
	MENU_NO	NUMBER		NOT NULL,
	CATEGORY	VARCHAR2(5)		NULL,
	MENU_KOR_NM	VARCHAR2(100)		NULL,
	MENU_ENG_NM	VARCHAR2(100)		NULL,
	DOC_ID	VARCHAR2(500)		NULL,
	MENU_DTL	VARCHAR2(500)		NULL,
	ORIG_AMT	NUMBER		NULL,
	SALE_AMT	NUMBER		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_MENU.MENU_TYP IS '메뉴타입(상품,메뉴)';

COMMENT ON COLUMN T_MENU.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_MENU.CATEGORY IS '카테고리';

COMMENT ON COLUMN T_MENU.MENU_KOR_NM IS '메뉴명';

COMMENT ON COLUMN T_MENU.MENU_ENG_NM IS '메뉴영문명';

COMMENT ON COLUMN T_MENU.DOC_ID IS '문서아이디';

COMMENT ON COLUMN T_MENU.MENU_DTL IS '메뉴상세';

COMMENT ON COLUMN T_MENU.ORIG_AMT IS '원가';

COMMENT ON COLUMN T_MENU.SALE_AMT IS '판매가격';

COMMENT ON COLUMN T_MENU.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_MENU.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_MENU.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_MENU_OPT;

CREATE TABLE T_MENU_OPT (
	MENU_NO	NUMBER		NOT NULL,
	OPT_NO	NUMBER		NOT NULL,
	OPT_NM	VARCHAR2(100)		NULL,
	OPT_AMT	NUMBER		NULL,
	DOC_ID	VARCHAR2(500)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_MENU_OPT.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_MENU_OPT.OPT_NO IS '옵션번호';

COMMENT ON COLUMN T_MENU_OPT.OPT_NM IS '옵션명';

COMMENT ON COLUMN T_MENU_OPT.OPT_AMT IS '가격';

COMMENT ON COLUMN T_MENU_OPT.DOC_ID IS '첨부파일';

COMMENT ON COLUMN T_MENU_OPT.DEL_YN IS '삭제일시';

COMMENT ON COLUMN T_MENU_OPT.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_MENU_OPT.LST_MODIFY_DTE IS '최근수정일시';

DROP TABLE T_BBS;

CREATE TABLE T_BBS (
	BBS_TYP	VARCHAR2(10)		NOT NULL,
	BBS_NO	NUMBER		NOT NULL,
	BBS_TITLE	VARCHAR2(200)		NULL,
	BBS_CONTENT	VARCHAR2(1000)		NULL,
	DOC_ID	VARCHAR2(500)		NULL,
	BBS_INS_DT	VARCHAR2(8)		NULL,
	BBS_LST_DT	VARCHAR2(8)		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_BBS.BBS_TYP IS '게시판유형(이벤트,공지)';

COMMENT ON COLUMN T_BBS.BBS_NO IS '게시판번호';

COMMENT ON COLUMN T_BBS.BBS_TITLE IS '제목';

COMMENT ON COLUMN T_BBS.BBS_CONTENT IS '내용';

COMMENT ON COLUMN T_BBS.DOC_ID IS '첨부파일번호';

COMMENT ON COLUMN T_BBS.BBS_INS_DT IS '게시일시';

COMMENT ON COLUMN T_BBS.BBS_LST_DT IS '게시마감일시';

COMMENT ON COLUMN T_BBS.USER_ID IS '게시자명';

COMMENT ON COLUMN T_BBS.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_BBS.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_BBS.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_ATTC_FILE;

CREATE TABLE T_ATTC_FILE (
	DOC_ID	VARCHAR2(500)		NOT NULL,
	FILE_SEQ	NUMBER		NULL,
	FILE_NM	VARCHAR2(200)		NULL,
	FILE_STOR_PATH	VARCHAR2(1000)		NULL,
	FILE_EXT	VARCHAR2(100)		NULL,
	FILE_TYP	VARCHAR2(100)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	VARCHAR2(255)	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_ATTC_FILE.DOC_ID IS '문서아아디';

COMMENT ON COLUMN T_ATTC_FILE.FILE_NM IS '파일명';

COMMENT ON COLUMN T_ATTC_FILE.FILE_STOR_PATH IS '저장경로';

COMMENT ON COLUMN T_ATTC_FILE.FILE_EXT IS '파일확장자';

COMMENT ON COLUMN T_ATTC_FILE.FILE_TYP IS '파일타입';

COMMENT ON COLUMN T_ATTC_FILE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_ATTC_FILE.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_ATTC_FILE.LST_MODIFY_DTE IS '최종수정일자';

DROP TABLE T_CMN_CD;

CREATE TABLE T_CMN_CD (
	CMN_CD	VARCHAR2(100)		NOT NULL,
	CMN_CD_NM	VARCHAR2(100)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);



--DROP TABLE T_CMN_CD;

CREATE TABLE T_CMN_CD (
	CMN_CD	VARCHAR2(100)		NOT NULL,
	CMN_CD_NM	VARCHAR2(100)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_CMN_CD.CMN_CD IS '코드번호';

COMMENT ON COLUMN T_CMN_CD.CMN_CD_NM IS '코드명';

COMMENT ON COLUMN T_CMN_CD.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_CMN_CD.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_CMN_CD.LST_MODIFY_DTE IS '최종수정일자';

DROP TABLE T_MENU_MNG;

CREATE TABLE T_MENU_MNG (
	INVENT_NO	VARCHAR2(255)		NOT NULL,
	MENU_NO	VARCHAR2(255)		NOT NULL,
	INVENT_CNT	VARCHAR2(255)		NULL,
	RECV_DTE	VARCHAR2(255)		NULL,
	INVENT_AMT	VARCHAR2(255)		NULL,
	DEL_YN	VARCHAR2(255)	DEFAULT 'N'	NULL,
	FST_INS_DTE	VARCHAR2(255)	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	VARCHAR2(255)	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_MENU_MNG.INVENT_NO IS '재고번호';

COMMENT ON COLUMN T_MENU_MNG.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_MENU_MNG.INVENT_CNT IS '수량';

COMMENT ON COLUMN T_MENU_MNG.RECV_DTE IS '입고날짜';

COMMENT ON COLUMN T_MENU_MNG.INVENT_AMT IS '가격';

COMMENT ON COLUMN T_MENU_MNG.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_MENU_MNG.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_MENU_MNG.LST_MODIFY_DTE IS '최총수정일자';

DROP TABLE T_WISH;

CREATE TABLE T_WISH (
	WISH_NO	NUMBER		NOT NULL,
	USER_ID	VARCHAR2(20)		NULL,
	MENU_NO	NUMBER		NULL,
	WISH_DTE	VARCHAR2(8)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_WISH.WISH_NO IS '찜 번호';

COMMENT ON COLUMN T_WISH.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_WISH.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_WISH.WISH_DTE IS '일시';

COMMENT ON COLUMN T_WISH.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_WISH.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_WISH.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_REVIEW;

CREATE TABLE T_REVIEW (
	REVIEW_NO	NUMBER		NOT NULL,
	REVIEW_TITLE	VARCHAR2(1000)		NULL,
	REVIEW_CONTENT	VARCHAR2(2000)		NULL,
	REVIEW_DTE	VARCHAR2(8)		NULL,
	REVIEW_POINT	NUMBER		NULL,
	DOC_ID	VARCHAR2(500)		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	MENU_NO	NUMBER		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_REVIEW.REVIEW_NO IS '리뷰번호';

COMMENT ON COLUMN T_REVIEW.REVIEW_TITLE IS '리뷰제목';

COMMENT ON COLUMN T_REVIEW.REVIEW_CONTENT IS '리뷰내용';

COMMENT ON COLUMN T_REVIEW.REVIEW_DTE IS '리뷰일시';

COMMENT ON COLUMN T_REVIEW.REVIEW_POINT IS '별점';

COMMENT ON COLUMN T_REVIEW.DOC_ID IS '문서아이디';

COMMENT ON COLUMN T_REVIEW.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_REVIEW.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_REVIEW.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_REVIEW.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_REVIEW.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_CART;

CREATE TABLE T_CART (
	CART_NO	NUMBER		NOT NULL,
	CART_TYP	NUMBER		NOT NULL,
	CART_DTE	VARCHAR2(8)		NULL,
	MENU_NO	NUMBER		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	CART_CNT	NUMBER		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_CART.CART_NO IS '장바구니번호';

COMMENT ON COLUMN T_CART.CART_TYP IS '잦바구니타입(픽업,배송)';

COMMENT ON COLUMN T_CART.CART_DTE IS '장바구니일시';

COMMENT ON COLUMN T_CART.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_CART.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_CART.CART_CNT IS '수량';

COMMENT ON COLUMN T_CART.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_CART.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_CART.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_ORDER;

CREATE TABLE T_ORDER (
	ORDER_NO	NUMBER		NOT NULL,
	ORDER_TYP	NUMBER		NOT NULL,
	ORDER_DTE	DATE		NULL,
	ORDER_TOT_AMT	NUMBER		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	ORDER_ADDR	VARCHAR2(500)		NULL,
	STATUS	VARCHAR2(1)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);


COMMENT ON COLUMN T_ORDER.ORDER_NO IS '주문번호';

COMMENT ON COLUMN T_ORDER.ORDER_TYP IS '주문타입(픽,배)';

COMMENT ON COLUMN T_ORDER.ORDER_DTE IS '주문일시';

COMMENT ON COLUMN T_ORDER.ORDER_TOT_AMT IS '주문총액';

COMMENT ON COLUMN T_ORDER.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_ORDER.ORDER_ADDR IS '주문자주소';

COMMENT ON COLUMN T_ORDER.STATUS IS '주문상태';

COMMENT ON COLUMN T_ORDER.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_ORDER.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_ORDER.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_PICKUP;

CREATE TABLE T_PICKUP (
	ORDER_NO	NUMBER		NOT NULL,
	OFFICE_NO	NUMBER		NULL,
	PICK_DTE	DATE		NULL,
	PICK_STATUS	VARCHAR2(1)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN T_PICKUP.ORDER_NO IS '주문번호';

COMMENT ON COLUMN T_PICKUP.OFFICE_NO IS '주문매장번호';

COMMENT ON COLUMN T_PICKUP.PICK_DTE IS '픽업일시';

COMMENT ON COLUMN T_PICKUP.PICK_STATUS IS '픽업상태';

COMMENT ON COLUMN T_PICKUP.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_PICKUP.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_PICKUP.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_ORDER_DTL;

CREATE TABLE T_ORDER_DTL (
	ORDER_NO	NUMBER		NOT NULL,
	MENU_NO	NUMBER		NULL,
	ORDER_CNT	NUMBER		NULL,
	ORDER_AMT	NUMBER		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_ORDER_DTL.ORDER_NO IS '주문번호';

COMMENT ON COLUMN T_ORDER_DTL.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN T_ORDER_DTL.ORDER_CNT IS '주문수량';

COMMENT ON COLUMN T_ORDER_DTL.ORDER_AMT IS '주문가격';

COMMENT ON COLUMN T_ORDER_DTL.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_ORDER_DTL.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_ORDER_DTL.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_RESERVE;

CREATE TABLE T_RESERVE (
	RESV_NO	NUMBER		NOT NULL,
	RESV_DTE	VARCHAR2(8)		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	RESV_TITLE	VARCHAR2(500)		NULL,
	RESV_CONTENT	VARCHAR2(1000)		NULL,
	RESV_ST_DTE	VARCHAR2(8)		NULL,
	RESV_ST_TIME	VARCHAR2(4)		NULL,
	RESV_ED_DTE	VARCHAR2(8)		NULL,
	RESV_ED_TIME	VARCHAR2(4)		NULL,
	RESV_PHONE_NUM	VARCHAR2(20)		NULL,
	OFFICE_NO	NUMBER		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_RESERVE.RESV_NO IS '예약번호';

COMMENT ON COLUMN T_RESERVE.RESV_DTE IS '예약일시';

COMMENT ON COLUMN T_RESERVE.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_RESERVE.RESV_TITLE IS '예약주제';

COMMENT ON COLUMN T_RESERVE.RESV_CONTENT IS '예약내용';

COMMENT ON COLUMN T_RESERVE.RESV_ST_DTE IS '예약시작날짜';

COMMENT ON COLUMN T_RESERVE.RESV_ST_TIME IS '예약시작시간';

COMMENT ON COLUMN T_RESERVE.RESV_ED_DTE IS '예약종료날짜';

COMMENT ON COLUMN T_RESERVE.RESV_ED_TIME IS '예약종료시간';

COMMENT ON COLUMN T_RESERVE.RESV_PHONE_NUM IS '연락처';

COMMENT ON COLUMN T_RESERVE.OFFICE_NO IS '지점번호';

COMMENT ON COLUMN T_RESERVE.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_RESERVE.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_RESERVE.LST_MODIFY_DTE IS '최종수정일자';

DROP TABLE T_QNA;

CREATE TABLE T_QNA (
	QNA_NO	NUMBER		NOT NULL,
	QNA_CATEGORY	VARCHAR2(5)		NULL,
	QNA_TITLE	VARCHAR2(500)		NULL,
	QNA_CONTENT	VARCHAR2(2000)		NULL,
	DOC_ID	VARCHAR2(500)		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	QNA_STS	VARCHAR2(1)		NULL,
	QNA_DTE	VARCHAR2(8)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_QNA.QNA_NO IS '문의번호';

COMMENT ON COLUMN T_QNA.QNA_CATEGORY IS '카테고리';

COMMENT ON COLUMN T_QNA.QNA_TITLE IS '문의제목';

COMMENT ON COLUMN T_QNA.QNA_CONTENT IS '문의내용';

COMMENT ON COLUMN T_QNA.DOC_ID IS '문서아이디';

COMMENT ON COLUMN T_QNA.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_QNA.QNA_STS IS '문의상태';

COMMENT ON COLUMN T_QNA.QNA_DTE IS '문의일시';

COMMENT ON COLUMN T_QNA.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_QNA.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_QNA.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_QNA_ANS;

CREATE TABLE T_QNA_ANS (
	QNA_NO	NUMBER		NOT NULL,
	ANS_CONTENT	VARCHAR2(2000)		NULL,
	ANS_DTE	VARCHAR2(8)		NULL,
	USER_ID	VARCHAR2(20)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_QNA_ANS.QNA_NO IS '문의번호';

COMMENT ON COLUMN T_QNA_ANS.ANS_CONTENT IS '답변내용';

COMMENT ON COLUMN T_QNA_ANS.ANS_DTE IS '답변일시';

COMMENT ON COLUMN T_QNA_ANS.USER_ID IS '사용자아이디';

COMMENT ON COLUMN T_QNA_ANS.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_QNA_ANS.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_QNA_ANS.LST_MODIFY_DTE IS '최종수정일시';

DROP TABLE T_PAYMENT;

CREATE TABLE T_PAYMENT (
	ORDER_NO	NUMBER		NOT NULL,
	PAY_DTE	VARCHAR2(8)		NULL,
	PAY_METHOD	VARCHAR2(30)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_PAYMENT.ORDER_NO IS '주문번호';

COMMENT ON COLUMN T_PAYMENT.PAY_DTE IS '결제일시';

COMMENT ON COLUMN T_PAYMENT.PAY_METHOD IS '결제수단';

COMMENT ON COLUMN T_PAYMENT.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_PAYMENT.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_PAYMENT.LST_MODIFY_DTE IS '최종수정일시';

--DROP TABLE T_CMN_CD_DTL;

CREATE TABLE T_CMN_CD_DTL (
	CMN_CD	VARCHAR2(100)		NOT NULL,
	CMN_DTL_CD	VARCHAR2(100)		NULL,
	CMN_DTL_NM	VARCHAR2(100)		NULL,
	DEL_YN	VARCHAR2(1)	DEFAULT 'N'	NULL,
	FST_INS_DTE	DATE	DEFAULT SYSDATE	NOT NULL,
	LST_MODIFY_DTE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN T_CMN_CD_DTL.CMN_CD IS '공통코드';

COMMENT ON COLUMN T_CMN_CD_DTL.CMN_DTL_CD IS '공통상세코드';

COMMENT ON COLUMN T_CMN_CD_DTL.CMN_DTL_NM IS '상세코드명';

COMMENT ON COLUMN T_CMN_CD_DTL.DEL_YN IS '삭제여부';

COMMENT ON COLUMN T_CMN_CD_DTL.FST_INS_DTE IS '최초입력일시';

COMMENT ON COLUMN T_CMN_CD_DTL.LST_MODIFY_DTE IS '최종수정일시';

ALTER TABLE T_USER ADD CONSTRAINT PK_T_USER PRIMARY KEY (
	USER_ID
);

ALTER TABLE T_OFFICE ADD CONSTRAINT PK_T_OFFICE PRIMARY KEY (
	OFFICE_NO
);

ALTER TABLE T_MENU ADD CONSTRAINT PK_T_MENU PRIMARY KEY (
	MENU_TYP,
	MENU_NO
);

ALTER TABLE T_MENU_OPT ADD CONSTRAINT PK_T_MENU_OPT PRIMARY KEY (
	MENU_NO,
	OPT_NO
);

ALTER TABLE T_BBS ADD CONSTRAINT PK_T_BBS PRIMARY KEY (
	BBS_TYP,
	BBS_NO
);

ALTER TABLE T_ATTC_FILE ADD CONSTRAINT PK_T_ATTC_FILE PRIMARY KEY (
	DOC_ID,
	FILE_SEQ
);

ALTER TABLE T_CMN_CD ADD CONSTRAINT PK_T_CMN_CD PRIMARY KEY (
	CMN_CD
);

ALTER TABLE T_MENU_MNG ADD CONSTRAINT PK_T_MENU_MNG PRIMARY KEY (
	INVENT_NO,
	MENU_NO
);

ALTER TABLE T_WISH ADD CONSTRAINT PK_T_WISH PRIMARY KEY (
	WISH_NO
);

ALTER TABLE T_REVIEW ADD CONSTRAINT PK_T_REVIEW PRIMARY KEY (
	REVIEW_NO
);

ALTER TABLE T_CART ADD CONSTRAINT PK_T_CART PRIMARY KEY (
	CART_NO,
	CART_TYP
);

ALTER TABLE T_ORDER ADD CONSTRAINT PK_T_ORDER PRIMARY KEY (
	ORDER_NO,
	ORDER_TYP
);

ALTER TABLE T_PICKUP ADD CONSTRAINT PK_T_PICKUP PRIMARY KEY (
	ORDER_NO
);

ALTER TABLE T_ORDER_DTL ADD CONSTRAINT PK_T_ORDER_DTL PRIMARY KEY (
	ORDER_NO,
	MENU_NO
);

ALTER TABLE T_RESERVE ADD CONSTRAINT PK_T_RESERVE PRIMARY KEY (
	RESV_NO
);

ALTER TABLE T_QNA ADD CONSTRAINT PK_T_QNA PRIMARY KEY (
	QNA_NO
);

ALTER TABLE T_QNA_ANS ADD CONSTRAINT PK_T_QNA_ANS PRIMARY KEY (
	QNA_NO
);

ALTER TABLE T_PAYMENT ADD CONSTRAINT PK_T_PAYMENT PRIMARY KEY (
	ORDER_NO
);

ALTER TABLE T_CMN_CD_DTL ADD CONSTRAINT PK_T_CMN_CD_DTL PRIMARY KEY (
	CMN_CD,
	CMN_DTL_CD
);

